### ISSUE TITLE
Passowrd for login

### ISSUE THREAD

**Issue by rahulkhatry4** [bonfimtm/aden#1]
Hi 

Can you please tell the password for logging into the CMS.

Thanks

**Comment by bonfimtm** [comment]
Hi @rahulkhatry4,

First you should create your own [Firebase](https://firebase.google.com/) project where you can configure users and their passwords. Then configure the newly created project in the configuration files inside /src/environments/. Check Firebase [docs](https://firebase.google.com/docs/web/setup) for detailed information.
